### PR TITLE
Introduced async forms of timeout handlers

### PR DESCRIPTION
**Pull request by coreagile**
Figured I'll just create this PR just in case folks want it.

### CODE REVIEW

**Comment by weavejester** [comment]
It looks like you're treating the asynchronous handler as a synchronous one. I don't think this works, unless I'm missing something.

**Comment by coreagile** [comment]
Fascinating! I wish I knew why it worked for me. Looks like I'll be digging for a while!

**Comment by weavejester** [comment]
You might have supplied a handler with both synchronous and asynchronous arities.

**Comment by coreagile** [comment]
Ah makes sense. Thanks for putting up with my naïveté!

**Pull request closed without merging**
