### PR TITLE
Add ability to specify a timeout-handler fn

### PR DESCRIPTION
**Pull request by jcromartie**
This gives users the ability to specify a `timeout-handler` fn instead of a `timeout-response`, which is called with the original request in case of a timeout. This would let you implement things like redirecting to the original URL after login.

### CODE REVIEW

**Comment by weavejester** [comment]
The precondition for `timeout-handler` should be `ifn?` rather than `fn?`, and there should also be a precondition to ensure that `timeout-handler` and `timeout-response` cannot be both set at once.

**Comment by jcromartie** [comment]
Thanks. Updated.

**Comment by rlbdv** [comment]
I was just looking around for a way to handle redirections after (re)login; this would definitely be handy.

**Comment by Pancia** [comment]
Any plan to merge this in? Not having this is blocking me from using ring-session-timeout directly, just copy pasted the code in for now.

**Comment by weavejester** [comment]
I didn't get a notification for the last couple of messages for this PR, so I'm afraid it slipped through the cracks. I'll take another look at it.

**Comment by weavejester** [comment]
This looks good to merge. Sorry for the long delay. If you're still around, if you squash your commits and change the message to use the imperative mood (e.g. "add" instead of "adds"), we should be good to merge.

**Comment by jcromartie** [comment]
I'm not sure why but I also didn't get the last few notifications either. I will update it so it can be merged. Thanks.

**Comment by jcromartie** [comment]
Closing to create a new PR with squashed commits and updated message

**Comment by jcromartie** [comment]
Oops, I realized that I can probably just rebase this branch.

**Pull request merged**
